version: "3"
name: car-auction
services:
  web:
    image: car_auction_app
    build:
      context: .
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
  redis:
    image: redis:6.2-alpine
    container_name: car_auction_pg_redis
    ports:
      - '6379:6379'
  db:
    image: "postgres:15.3-bookworm"
    container_name: car_auction_pg_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql@15/data
volumes:
  data:
